### ISSUE TITLE
functions with too much stack usage 

### ISSUE THREAD

**Issue by redplait** [ANSSI-FR/libecc#18]
It seems that there are at least 3 functions with big stack usage:
_ecgdsa_verify_finalize
_ecrdsa_verify_finalize
_ecdsa_verify_finalize
this can be problem when using libecc inside windows driver bcs stack size is limited 12kb (see https://community.osr.com/discussion/45453/kernel-stack-limts)
So perhaps it has sense to add option something like ALLOW_EXTERNAL_ALLOCATION and add code like this
typedef u8 *(*Tbuf_alloc)(u32 size);
typedef void (*Tbuf_free)(u8 *);

extern Tbuf_alloc g_buf_alloc;
extern Tbuf_free g_buf_free;

next in each of above mentioned function:
`#ifdef ALLOW_EXTERNAL_ALLOCATION
u8 *h_buf = NULL;
...
	h_buf = g_buf_alloc(sizeof(u8) * MAX_DIGEST_SIZE);
	if ( h_buf == NULL )
        {
           ret = -1;
           goto err;
        }
...
err:
        if ( h_buf != NULL )
          g_buf_free(h_buf);
`

**Comment by rb-anssi** [comment]
Hi,

Thanks for your interest in libecc. Regarding the stack usage and dynamic allocation, the main issue is rather related to the internal structured types (natural numbers, Fp, curves) allocation on local variables and not on simple buffers as you point on hash buffers, and migrating to a dynamic allocation as you suggest will be quite difficult without dealing with possible leaks and heap issues.

Anyways, from your tests what is the overflow size on the stack for these functions compared to the 12Kb limit?

Regards,

**Comment by redplait** [comment]
well, I use only ec_verify_init/ec_verify_update/ec_verify_finalize in driver
seems that __chkstk called on ec_scalar_mult/generate_and_export_key_pair/store_sig/sign_bin_file/verify_bin_file too
now for example _ecgdsa_verify_finalize using 1070h on 32bit and 10F0h on 64
this is dangerously close to stack exhaustion

**Comment by rb-anssi** [comment]
Agreed for the high stack usage: the choice has been made (for security reasons) to avoir dynamic allocation, and this is somehow the price to pay. Some tips to limit this stack usage: depending on the curves you indeed use, you can squeeze down the structures size by removing some curves: 256 bits curves only will take less place than 521 bits ones. You can perform tuning in `src/lib_ecc_config.h`. Although this is not a generic solution, this could help your specific case if you can afford to stick to <= 256 bits curves.

Regards,

**Comment by rb-anssi** [comment]
By the way, and from the thread https://community.osr.com/discussion/45453/kernel-stack-limts you have pointed: isn't it possible to increase stack usage by using another worker thread (with more stack size) inside the module? Sorry if this question is rather naive, my development skills in windows drivers are quite limited ...

Regards,

**Comment by redplait** [comment]
it`s possible but requires to change code - for example to add worker, put tasks of signs checking to it and then waiting for results. Lots of code and painful debugging
For now I just add allocation of prj_pt - seems that _ecrdsa_verify_finalize now using 840h of stack + allocating 8E8h from heap. Much better
See sample in attach
[ecrdsa.zip](https://github.com/ANSSI-FR/libecc/files/6116760/ecrdsa.zip)
