### ISSUE TITLE
conversion from 'word_t' to 'u8', possible loss of data

### ISSUE THREAD

**Issue by redplait** [ANSSI-FR/libecc#19]
visual studio 2017 claims twice when compiling nn\nn_add.c
line 125:  out->wlen += carry;
line 194: out->wlen += carry;
perhaps type conversion can help: out->wlen += (u8)carry;

**Comment by rb-anssi** [comment]
Hi,

Thanks for the feedback! Visual Studio is indeed right here, weird that gcc and clang did not catch it :-)
This should be fixed in commit e42f30ee13e98ecd3b5663dd87d25c63161bf047

Regards,

**Comment by rb-anssi** [comment]
Issue closed since fixed in commit.
