### ISSUE TITLE
Signature function's "help" function is incorrect

### ISSUE THREAD

**Issue by OluAgunloye** [ANSSI-FR/libecc#22]
Hello @rb-anssi and @ae-anssi !

Branch: master

Version: most recent as of now

Error:
```
./ec_utils verify
Bad args number for ./ec_utils verify:
        arg1 = curve name: FRP256V1 SECP192R1 SECP224R1 SECP256R1 SECP384R1 SECP521R1 BRAINPOOLP192R1 BRAINPOOLP224R1 BRAINPOOLP256R1 BRAINPOOLP384R1 BRAINPOOLP512R1 GOST256 GOST512 SM2P256TEST SM2P256V1 WEI25519 WEI448 
        arg2 = signature algorithm type: ECDSA ECKCDSA ECSDSA ECOSDSA ECFSDSA ECGDSA ECRDSA SM2 EDDSA25519 EDDSA25519CTX EDDSA25519PH EDDSA448 EDDSA448PH 
        arg3 = hash algorithm type: SHA224 SHA256 SHA384 SHA512 SHA512_224 SHA512_256 SHA3_224 SHA3_256 SHA3_384 SHA3_512 SM3 SHAKE256 
        arg4 = input file to verify
        arg5 = input file containing the public key (in raw binary format)
        <arg7 (optional) = ancillary data to be used>
```

Solution:

This should be superseded by the instructions for using the signature function in the current, outermost README file (the one displayed on this repo's Github address).  That is to say:

`$ ./build/ec_utils verify <CURVE> <SIGNATURE ALGO> <HASH>  examplefile  example_public_key.bin  example_signed_file.bin`

**Comment by rb-anssi** [comment]
Hi @OluAgunloye !

Thanks for your interest in libecc of for this feedback, however this issue should only concern the eddsa-sm2 and eddsa-sm2-api development branches, not the master branch as the ancillary data option have been introduced only there for now.

We will update the documentation accordingly on these branches, but please keep in mind if you have checkout those two that they are still work in progress, and might be unstable (only the master branch can be considered as stable).

Regards,
