### ISSUE TITLE
Am I allowed to include the source of this in a project with a GPLv2 license?

### ISSUE THREAD

**Issue by MFDGaming** [ANSSI-FR/libecc#26]

**Comment by rb-anssi** [comment]
Hi @MFDGaming,

Yes of course you can include this project in other GPLv2 projets since they share the same licence (libecc has a dual licencing mode, meaning that you can choose between BSD and GPLv2, for GPLv2 project this seems natural to choose the latter).

Regards,

**Comment by MFDGaming** [comment]
Good to know thanks, just asked cause I was concerned if it was legal to do so.
