### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by atxr** [ANSSI-FR/libecc#28]
Is any documentation available for this library?

**Comment by rb-anssi** [comment]
Hi,

The main documentation of libecc is in the README.md file of the repository (the library rationale, features and architecture are explained there). Although there is no detailed (doxygen like) documentation about the API, many examples are present in the source code (mainly in the self tests and utilities compiled by the Makefile, and in the `src/examples` folder).

High level APIs handling EC signatures and ECDH should be quite straightforward to use (low level NN and Fp APIs might be a bit more complex to use, but examples should help).

Regards,

**Comment by atxr** [comment]
Thank you for your answer. I was indeed looking for some kind of doxygen documentation, but the provided example will suffice.
