### ISSUE TITLE
prj_pt_monty.c is missing

### ISSUE THREAD

**Issue by goldentechie** [ANSSI-FR/libecc#36]
`/Users/admin/Documents/****/lib/libecc/src/curves/prj_pt_monty.c Build input file cannot be found: '/Users/admin/Documents/****/lib/libecc/src/curves/prj_pt_monty.c'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?
`

I got this error while I was building an iOS project. The repository does not have the files, but the xcode project requires them. How to fix it?

**Comment by rb-anssi** [comment]
Hi,

What `xcode` project are you building?
The `prj_pt_monty.c` was indeed a file in the project, but has disappeared after some code cleaning and commits a while ago. It seems that your iOS project makes reference to an old version of the libecc repository: you should update this project to include the current files.

Regards,

**Comment by ae-anssi** [comment]
Hi,

src/curves/prj_pt_monty.c is gone since commit b8739816 (Sep 23 2021). AFAICT, it is no more referenced in the libecc project Makefile. I think the reference to the file was somehow cached in your xcode project on your side.

Cheers,

a+

**Comment by goldentechie** [comment]
Thank you so much @ae-anssi , @rb-anssi .

I got to know that I used an old commit of this project. a6fa90a218a547cae8a4dfd31837a0ceae7bc7ce

**Comment by rb-anssi** [comment]
@goldentechie : we strongly advise you tu update to the newer upstream version as many elements have been fixed, simplified, and so on :-)

Regards,

**Comment by goldentechie** [comment]
Will do! Thank you.👍
